### PR TITLE
DOC-5269

### PR DESCRIPTION
**Pull request by jamesnocentini**
https://issues.couchbase.com/browse/DOC-5269

docs-site PR https://github.com/couchbase/docs-site/pull/85
Preview https://deploy-preview-85--cb-docs-staging.netlify.com/home/index.html

### CODE REVIEW

**Comment by jamesnocentini** [comment]
@eric-schneider @tonyjhillman this PR increases the content width for large screens from 80 rem to 90 rem, resulting in less whitespace on either side.

**Comment by eric-schneider** [comment]
@jamiltz Wow it makes a big difference! This is definitely the way we want to go. Now, I'm wondering if we should maybe scale back the content width a couple of rem and increase the ToC rem by a couple. What do you think @tonyjhillman?

**Comment by jamesnocentini** [comment]
@eric-schneider I've increased the width to 15rem which forces the content width down. Having the wider ToC is a very noticeable improvement.

**Comment by eric-schneider** [comment]
@jamiltz The preview site you provided shows a wider in-page ToC but the component ToC seems the same. I think the left nav needs more space. The right nav can probably stay the same for now. I think reducing font size in the right nav will go a long way.

**Comment by mojavelinux** [comment]
I'd be extremely careful with reducing the content width at all. That's only going to exasperate the problem you have with really wide tables. So I'd just recommend that you look into that before making the change.

**Comment by eric-schneider** [comment]
> I'd be extremely careful with reducing the content width at all.

I don't think we're reducing content width at all. I think we should look at the overall max page width, and divide it between left-nav, content, and right-nav.

Though, after our team meeting today, we're going to hold off on changing the nav widths until we switch fonts.

**Comment by jamesnocentini** [comment]
After the team meeting, we've concluded to only increase content width and see how that helps the really wide tables. Left nav and in-page ToC widths are unchanged.

**Pull request merged**
