### PR TITLE
WIP: UI for tutorial pages

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@jamiltz You don't need to check the UI bundle directly into the git repository. Instead, if you send a (long-running) pull request, you can access the UI bundle via the Netify preview URL (at the /dist/ui-bundle.zip path). In this case, the UI bundle is available at the following URL.

https://deploy-preview-47--cb-docs-ui.netlify.com/dist/ui-bundle.zip

Each time you push a commit to the branch, the UI bundle will be updated (so in the playbook file, you'll want to enable the snapshot flag).

**Comment by mojavelinux** [comment]
Here's where the Gulp build puts the UI bundle into the preview site:

https://github.com/couchbase/docs-ui/blob/5dac9545eb8fdc747b1907917df6c0aa478c84d2/gulpfile.js#L17

**Comment by jamesnocentini** [comment]
@mojavelinux I'm getting back to working on this task. Ok will do that, thanks!

**Comment by jamesnocentini** [comment]
Closing this PR and opened a new one in order to rename the base branch https://github.com/couchbase/docs-ui/pull/49.

**Pull request closed without merging**
