### PR TITLE
DOC-5725 Replace JIRA Issue Collector

### PR DESCRIPTION
**Pull request by amarantha-k**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@mojavelinux Would it be a concern if we specify the collectorId in the URL itself?

**Comment by mojavelinux** [comment]
I don't think it's a good idea to hard code it because then it's more effort to customize. Is there a reason you want to hard code it?

**Comment by amarantha-k** [comment]
The Issue Collector issue has been open for a long time now and I was looking at every possible option to reduce variables and see if we can get it to work. 
And this morning we realized that with no code change by IT or me, we see that the Feedback button is now loading on Chrome/Firefox/Safari again!

**Comment by mojavelinux** [comment]
That's great to hear! :tada: I'm pretty sure the problem was on the JIRA end. So whatever change was made there, it seemed to have fixed it.

**Comment by mojavelinux** [comment]
Shall we close this PR?

**Comment by amarantha-k** [comment]
Closing without merge as the issue is resolved.

**Pull request closed without merging**
