### PR TITLE
Updates for archive site

### PR DESCRIPTION
**Pull request by mojavelinux**
Updates to accommodate requirements for the archive site. These changes will eventually get rolled into the main UI, but that will require upgrading to Antora 2.3.

### CODE REVIEW

**Comment by mojavelinux** [comment]
@amarantha-k The changes necessary to make the archive site work with the production UI applied are now minimal. This additional logic will only active when used on the archive site. It really comes down to two things:

1. Point View Latest to the production site (the "preferred" version)
2. Hide components that are only in the production site (since it would be confusing otherwise)

**Comment by amarantha-k** [comment]
@mojavelinux The code looks ok to me, don't think I can verify as the additional logic will only be active on the archive site.

**Review by amarantha-k — APPROVED** [review]

**Comment by mojavelinux** [comment]
You can verify using the private URL for the archive site. I'll send it via e-mail.

**Comment by mojavelinux** [comment]
I'll also send a PR with this new UI to prod so we can see the deploy preview.

**Pull request merged**
