### PR TITLE
DOC-4138

### PR DESCRIPTION
**Pull request by jamesnocentini**
https://issues.couchbase.com/browse/DOC-4138

### CODE REVIEW

**Comment by jamesnocentini** [comment]
@mojavelinux I've merged this PR to fix the issue in production. But I'm sure there is a longer term fix, perhaps to stop using Antora versions in this way :)

__Context:__

The "View Latest" banner is displayed on pages belonging to the `userprofile-couchbase-mobile` component. This component is using multiple branches (Antora versions) to maintain distinct tutorial parts. And therefore, displays the "View Latest" banner:



This PR adds a page attribute to optionally remove the view latest banner.

**Comment by mojavelinux** [comment]
> This PR adds a page attribute to optionally remove the view latest banner.

What concerns me is that you are managing a component-wide setting using a page-level attribute...which means you have to remember to repeat this attribute for every page in the component. Better would be to check for the name of the component in the UI and disable the View Latest based on that property. Then, there is no need to alter the pages themselves.

> This component is using multiple branches (Antora versions) to maintain distinct tutorial parts. 

This is not a use case we've considered in Antora. We'd need to discuss it further to understand if this is the right use of versions and, if not, how else it would be done.

**Comment by eric-schneider** [comment]
> This is not a use case we've considered in Antora. We'd need to discuss it further to understand if this is the right use of versions and, if not, how else it would be done.

@mojavelinux @jamiltz Yes, in our case I'm wondering why we're not just including all of the tutorials in the left nav. I think you could still do development on separate branches, and include them all in the left-nav under headings.

**Comment by mojavelinux** [comment]
I've discussed this further with the Antora community and the consensus seems to be that different variations of a tutorial should be done as modules rather than versions. Whether you maintain those modules in separate branches is up to you. It's the versions that don't seem to me like the right fit.

**Comment by jamesnocentini** [comment]
@eric-schneider For the left nav, from what I could see, a left nav (nav.adoc) is tied to a component. At the moment, the user-profile content belongs to the [userpofile-couchbase-mobile](https://github.com/couchbaselabs/userprofile-couchbase-mobile/blob/standalone/content/antora.yml#L1) component. All other tutorial content belongs to the `tutorials` component. Because of the branching with versions I didn't want to include the user profile content in the `tutorials` component. Therefore we have two navs: [tutorials component nav](https://docs.couchbase.com/tutorials/mobile-travel-sample/introduction.html) and [userprofile-couchbase-mobile nav](https://docs.couchbase.com/userprofile-couchbase-mobile/standalone/userprofile/userprofile_basic.html). In other words, in the current components setup we can't include content from the user profile tutorials in the main nav. This is not optimal. Another reason the current setup needs to change.

@mojavelinux Different variations as distinct modules is an interesting idea. The `examples` folder contains the accompanying sample app source code. So from what I understand, that would mean the sample app code is moved from one folder to another. I'm not sure how git would handle cherry-picking on a file that has changed location. Apart from that interrogation, it sounds like a great idea.

**Comment by mojavelinux** [comment]
@jamiltz that would then be an argument for using different branches, but not different versions. Remember that there is no direct relationship between branches and versions. This gives you flexibility in how you use git for managing the content. In other words, when you find yourself needing to cherry-pick / merge to moving changes around, that's a good indicator you want to use branches. There are other trade-offs to consider, but it should become clear over time.

> a left nav (nav.adoc) is tied to a component.

That's not entirely true. By default, the `page.navigation` defaults to the navigation for the current component version. But you have access to the navigation of the entire site via `site.navigation` (a map) (e.g., site.navigation.server). For instance, that's how MuleSoft is able to display the navigation for the entire site on every page.

> in the current components setup we can't include content from the user profile tutorials in the main nav

...which means you can do this. You will need to add more logic to the template that outputs the navigation, though.

**Comment by jamesnocentini** [comment]
@mojavelinux That is noted, we'll remove the usage of `versions` regardless. Yes the main advantage we see for branches is the ability to cherry-pick rather than copy paste between folders on the same branch.
So under the new layout we might have the following:
- **branch:** standalone, **folder:** modules/userprofile-couchbase-mobile-standalone
- **branch:** query, **folder:** modules/userprofile-couchbase-mobile-query
- **branch:** sync, **folder:** modules/userprofile-couchbase-mobile-sync
- **branch:** backgroundfetch, **folder:** modules/userprofile-couchbase-mobile-backgroundfetch

I've tried it and can confirm git has successfully cherry-picked a commit from the `standalone` branch to `query` even though the content had moved (from `modules/userprofile-couchbase-mobile-standalone` to `modules/userprofile-couchbase-mobile-query`). I wasn't sure if git cherry-picks would handle that but now it's clear it does. That could definitely be useful for larger updates to the content. Thanks!

> By default, the page.navigation defaults to the navigation for the current component version. But you have access to the navigation of the entire site via site.navigation (a map) (e.g., site.navigation.server).

Good to know about!

**Pull request merged**
